import { Box, Typography } from '@mui/material'
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import Home from './Home'
import About from './about'
import Experience from './Experience'
import Skills from './Skills'
import Contact from './Contact'

export default function Index() {
    return (
        <Box className={styles.container}>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <Header />

            <Box id='home'>
                <Home />
            </Box>

            <Box id='about'>
                <About />
            </Box>

            <Box id='experience'>
                <Experience />
            </Box>

            <Box id='skills'>
                <Skills />
            </Box>

            <Box id='contact'>
                <Contact />
            </Box>

            <Footer />
        </Box>
    )
}
